export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const USER_LOGOUT = 'USER_LOGIN_FAIL'


export const ALL_USERS_REQUEST = 'ALL_USERS_REQUEST'
export const ALL_USERS_SUCCESS = 'ALL_USERS_SUCCESS'
export const ALL_USERS_FAIL = 'ALL_USERS_FAIL'


export const USER_PROFILE_REQUEST = 'USERS_PROFILE_REQUEST'
export const USER_PROFILE_SUCCESS = 'USERS_PROFILE_SUCCESS'
export const USER_PROFILE_FAIL = 'USERS_PROFILE_FAIL'

export const DELETE_USER = 'DELETE_USER'